### ISSUE TITLE
Reddit Front Page link erroneously tries to load /r/redditfrontpage

### ISSUE THREAD

**Issue by zagaberoo** [zagaberoo/diode#75]

**Comment by Protuhj** [comment]
That change is just a quality of life change. Since you can't have spaces in subreddits, and most autocorrect features on phones will add spaces after words, this removes the spaces in between whole words.

The createSubredditUri should have been updated, or there should have been a check for the frontpage string before blindly removing spaces, but otherwise, I use the remove all spaces feature everything I use Diode.

**Comment by Jolt151** [comment]
I never actually realized what the point of that was. Yeah, that's super useful, and I'll be using that feature from now on.
